### ISSUE TITLE
failing test test_plane_mesh

### ISSUE THREAD

**Issue by smoors** [theochem/chemtools#18]
I think there are a few errors in the function `plane_mesh`: np.linspace needs scalars as the 2 first arguments, whereas arrays are supplied.
can you please take a look?
thank you in advance.

**Comment by smoors** [comment]
apparently recent numpy versions allow array-like start and stop values, sorry for the noise.

**Comment by FarnazH** [comment]
@smoors thanks for your interest in ChemTools. I just made a PR updating the numpy version requirement. Thanks for pointing this out.
